railsdemoapp/config/routes.rb
Ordermerchant::Application.routes.draw do
  resources :items

  get "/", :to => "order#new"
  get "/order/new" => "order#new"
  post "/order/create" => "order#create"
  post "/order/update/:id" => "order#update"
  get "/order/show/:id" => "order#show"
  get "/order/display/:id" => "order#display", :as => :order_display
end

railsdemoapp/app/models/item.rb
class Item < ActiveRecord::Base
end

railsdemoapp/app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :item
end

railsdemoapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

railsdemoapp/app/controllers/order_controller.rb
class OrderController < ApplicationController

  def new
    @items = Item.all
  end

  def create
    order = Order.create(:item_id => params[:item_id], :quantity => params[:quantity],:customer_name => params[:customer_name], :address => params[:address], :status=> 'New')
    redirect_to :action => :display, :id => order.id
  end

  def show
    @order = Order.find(params[:id])
    @item = Item.find(@order.item_id)
    render :json => {:order_id => @order.id , :item_name => @item.name , :status => @order.status, :quantity => @order.quantity, :address => @order.address, :customer_name => @order.customer_name}
  end

  def update
    @order = Order.find(params[:id])
    @order.status=params[:status]
    @order.save!
  end

  def display
    @order = Order.find(params[:id])

  end

end

railsdemoapp/app/helpers/application_helper.rb
module ApplicationHelper
end

railsdemoapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ordermerchant</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>

  <%=  content_for :head  %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

railsdemoapp/app/views/order/display.html.erb
<div class="container">
  <div>
    <h3 style="float:right">Order Status: <b style="color:red"><%= @order.status %></b></h3>
    <h3 style="float:left">Order Placed Successfully!</h3>

  </div>
  <div class="well container">
    <table class="table table-striped">
      <tr>
        <td>Customer Name</td>
        <td>Item Name</td>
        <td>Quantity</td>
        <td>Address</td>
      </tr>
      <tr>
        <td><%= @order.customer_name %> </td>
        <td><%= @order.item.name %> </td>
        <td><%= @order.quantity %></td>
        <td><%= @order.address %></td>
      </tr>
    </table>
  </div>
  <div>Please refresh this page to know the status of the shipment</div>
</div>

<div class="navbar navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand">Sample Rails App for demonstration purpose</div>
    </div>
  </div>
</div>

railsdemoapp/app/views/order/new.html.erb
<%= form_tag order_create_path, :method => 'post' do %>

    <div class="well container">
      <div class="brand well"><h1>Place your order...</h1></div>
      <form class="form-horizontal">
        <div class="control-group">
          <%= label_tag "customer_name", nil, :class => "control-label" %>
          <%= text_field_tag 'customer_name', nil, :class => "controls" %>
        </div>

        <div class="control-group">
          <%= label_tag "item", nil, :class => "control-label" %>
          <%= select_tag 'item_id', options_for_select(@items.collect { |item| [item.name, item.id] }), :class => "input-large shadow_select" %>
        </div>
        <div class="control-group">
          <%= label_tag "quantity", nil, :class => "control-label" %>
          <%= text_field_tag 'quantity', nil, :class => "controls" %>
        </div>
        <div class="control-group">
          <%= label_tag "address", nil, :class => "control-label" %>
          <%= text_area_tag 'address', nil, :class => "controls" %>
        </div>

        <%= submit_tag "Place Order", :class => "btn btn-primary" %>
      </form>
    </div>
<% end %>

<div class="navbar navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container">
      <div class="brand">Sample Rails App for demonstration purpose</div>
    </div>
  </div>
</div>